input("press enter to start")
retry = 0
duck = input("who should be the mc?")
food = input(f"what should the {duck} want? (name a food)")
supermarket = input(f"where could you get {food}")
lemonade = input("what should the man be selling?")
if food == lemonade:
    while food == lemonade:
        
        print("don't make what the {duck} wants and what the man sells the same thing")
        input("")
        ttc = input("which one do you want to change (type food or store)")
        if ttc != "food" and ttc != "store":
            input("I hate you")
        if ttc == food:
            food == input("what should the new food be")
        if ttc == store:
            lemonade == input("what should the new food be")
        retry += 1

retry = 0

input("3")
input("2")
input("1")
input(f"the {duck} walked up to the {lemonade} stand and said to the man running the stand")
input("hey!")
input("bum bum bum")
input(f"got any {food}?")
input("the man said")
input("no,")
input(f"we just sell {lemonade}")
input("but it's cold and it's fresh and it's all home made!")
input("can I get you a glass?")
input("I'll pass")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("to the very next day")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input(f"and the {duck} walked up to the {lemonade} stand and he said to the man running the stand")
input("hey!")
input("bum bum bum")
input(f"got any {food}?")
input("the man said")
input("No!")
input(f"we just sell {lemonade}")
input("but it's cold and it's fresh and it's all home made!")
input("can I get you a glass?")
input("I'll pass")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("to the very next day")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input(f"and the {duck} walked up to the {lemonade} stand and he said to the man running the stand")
input("hey")
input("bum bum bum")
input(f"got any {food}?")
input("the man said")
input("NO!")
input("and it's finally time")
input("If you come back here i'll glue you to that pine!")
input("I'll pass")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("waddle waddle")
input("and he waddled away")
input("to the very next day")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input(f"when the {duck} walked up to the {lemonade} stand and he said to the man running the stand")
input("hey")
input("bum bum bum")
input("got any glue?")
input("the man said")
input("erm, well actually no,")
input(f"got any {food}?")
input("the man sighed,")
input("fine all right")
input("why don't we go to the store")
input(f"and get you some {food}")
input("all right!")
input("and they waddled away")
input("waddle waddle")
input("and they waddled away")
input("waddle waddle")
input("and they waddled away")
input("to the supermarket")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("bum")
input("when they got to the {supermarket}, the man said")
input(f"why don't we get you some {food}")
input(f"actually, I am not really hungry for {food} anymore")
input("but I could really go for some fresh, cold, homemade")
input(f"{lemonade}")

print("and that's the duck song!")
input("")
yon = input("was that fun?")
if yon != yes and yon != y and yon != yep and yon != aboslutly and yon != yeah:
    print("bruh")
    input("why?")
    print("I honestly don't care in the slightest")